In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn 
import seaborn as sn
%matplotlib inline

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

In [25]:
df=pd.DataFrame(irisData.data,columns=irisData.feature_names)

In [27]:
df['target']=irisData.target

In [28]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [11]:
irisData=load_iris()

In [13]:
X=irisData.data
print(X[:5])
print(X.shape)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
(150, 4)


In [14]:
irisData.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [15]:
irisData.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [18]:
y=irisData.target
print(y[:5])

[0 0 0 0 0]


In [33]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [21]:
classifier=LogisticRegression()

In [22]:
classifier.fit(X_train,y_train)

LogisticRegression()

In [31]:
X_test

array([[5.1, 2.5, 3. , 1.1],
       [5.6, 2.7, 4.2, 1.3],
       [6.7, 3.3, 5.7, 2.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [6.5, 3. , 5.5, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.3, 3.4, 5.6, 2.4],
       [6.3, 2.3, 4.4, 1.3],
       [5.4, 3.4, 1.5, 0.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.3, 2.7, 4.9, 1.8],
       [4.3, 3. , 1.1, 0.1],
       [6. , 2.2, 5. , 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [4.9, 2.5, 4.5, 1.7],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2.5, 3.9, 1.1],
       [6.4, 2.8, 5.6, 2.2],
       [6.5, 3.2, 5.1, 2. ],
       [6.1, 2.8, 4. , 1.3],
       [4.4, 3.2, 1.3, 0.2],
       [5.7, 2.9, 4.2, 1.3],
       [5.2, 3.5, 1.5, 0.2],
       [5.6, 3. , 4.5, 1.5],
       [7.7, 2.6, 6.9, 2.3],
       [5.5, 2.4, 3.7, 1. ],
       [6.3, 2.5, 4.9, 1.5],
       [5. , 3.4, 1.5, 0.2],
       [6.3, 2.5, 5. , 1.9]])

In [29]:
y_test

array([1, 1, 2, 0, 0, 2, 2, 2, 1, 0, 1, 2, 0, 2, 1, 2, 0, 1, 2, 2, 1, 0,
       1, 0, 1, 2, 1, 1, 0, 2])

In [35]:
y_pred=classifier.predict(X_test)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [36]:
from sklearn.metrics import accuracy_score
print('accuracy:',accuracy_score(y_test,y_pred))

accuracy: 1.0
